### ISSUE TITLE
Plugin not working on export

### ISSUE THREAD

**Issue by Flowcheer** [belzecue/arlez80_godot-mod-player#1]
Godot 4.3
# Steps to reproduce
- Use the modplayer node in any scene
- Try exporting your project
- ModPlayer node doesnt work and throws: 
`SCRIPT ERROR: Cannot call method 'get_error' on a null value.
          at: Mod.read_file (res://addons/modplayer/Mod.gd:119)
SCRIPT ERROR: Invalid access to property or key 'data' on a base object of type 'Nil'.
          at: ModPlayer._prepare_to_play (res://addons/modplayer/ModPlayer.gd:518)`
This doesnt happen when you try playing from the editor

**Comment by Flowcheer** [comment]
Sorry, i didnt see this repo was outdated

**Comment by belzecue** [comment]
FYI for everyone:
Original repo on Bitbucket at https://bitbucket.org/arlez80/godot-mod-player/src/master/
Original author's site: https://arlez80.net/
